const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../core.js');
function game(){const g=C.createGame();g.mode='playing';return g;}
function run(g,input,n){for(let i=0;i<n;i++)C.step(g,input,1/120);}
test('Landning, rörelse och världens kanter',()=>{const g=game();run(g,{},60);assert.equal(g.p.y,418);assert.equal(g.p.grounded,true);run(g,{left:true},120);assert.equal(g.p.x,0);run(g,{right:true},100);assert(g.p.x>250);});
test('Hopp och flygkraft förbrukas, fylls på vid landning',()=>{const g=game();run(g,{},30);run(g,{jump:true},220);assert.equal(g.p.fuel,0);assert(g.p.y<418);run(g,{},180);assert(g.p.grounded);assert.equal(g.p.fuel,C.FUEL);});
test('Magi tar bort törnen och har återhämtning',()=>{const g=game();run(g,{},30);g.p.x=450;run(g,{magic:true},20);assert(g.thorns[0].removed);assert(g.cooldown>0);assert.equal(g.shots.length,0);});
test('Stjärnor räknas en gång',()=>{const g=game();g.p.x=280;g.p.y=418;run(g,{},60);assert.equal(g.collected,1);run(g,{},60);assert.equal(g.collected,1);});
test('Törnen, kort skydd, fall och förlust',()=>{const g=game();g.p.x=580;g.p.y=418;run(g,{},1);assert.equal(g.p.health,2);g.p.x=580;g.p.y=418;run(g,{},1);assert.equal(g.p.health,2);g.p.y=800;run(g,{},1);assert.equal(g.p.health,1);g.p.y=800;run(g,{},1);assert.equal(g.mode,'lost');});
test('Plattform stoppar från sidan och går att landa på',()=>{const g=game();g.p.x=1184;g.p.y=300;run(g,{right:true},1);assert(g.p.x<=1270-g.p.w);g.p.x=1340;g.p.y=180;g.p.vy=150;run(g,{},100);assert.equal(g.p.y,365-g.p.h);assert(g.p.grounded);});
test('Hela banan går att klara utan att flytta spelaren i testet',()=>{const g=game();for(let i=0;i<8000&&g.mode==='playing';i++){const p=g.p;const needJump=C.gaps.some(a=>p.x>a.x-140&&p.x<a.x+a.w+40)||C.hurdles.some(a=>p.x>a.x-160&&p.x<a.x+a.w+60);C.step(g,{right:true,jump:needJump&&(!p.grounded||!g.jumpWas),magic:i%90===0},1/120);}assert.equal(g.mode,'won');assert.equal(g.p.health,3);assert(g.collected>=5);});
test('Pausen fryser simulationen och start ger nytt spel',()=>{const g=game();g.mode='paused';run(g,{right:true},100);assert.equal(g.p.x,140);assert.equal(C.createGame().collected,0);});
function rideToParty(g,fly=true){for(let i=0;i<8000&&g.mode==='playing';i++){const p=g.p,near=C.gaps.some(a=>p.x>a.x-120&&p.x<a.x+a.w+40)||C.hurdles.some(a=>p.x>a.x-120&&p.x<a.x+a.w+60);C.step(g,{right:true,jump:near&&(fly?(!p.grounded||!g.jumpWas):p.grounded&&!g.jumpWas),magic:i%90===0},1/120);}}
test('Banan är mer än dubbelt så lång och kan klaras med korta hopp utan flygning',()=>{const g=game();assert(C.W>3900*2);assert(C.gaps.every(a=>a.w<=130));rideToParty(g,false);assert.equal(g.mode,'won');assert.equal(g.p.health,3);assert.equal(g.zone,5);});
test('Godis samlas en gång och magiska presenter ger en enda belöning',()=>{const g=game(),s=g.candies[0];g.p.x=s.x-40;g.p.y=418;run(g,{},30);assert.equal(g.candyCount,1);run(g,{},30);assert.equal(g.candyCount,1);g.p.x=2350;run(g,{magic:true},100);assert(g.activities[0].done);assert.equal(g.candyCount,5);run(g,{},100);run(g,{magic:true},100);assert.equal(g.candyCount,5);});
test('Hästvännen väntar på tre morötter och belönar bara en gång',()=>{const g=game();g.p.x=4250;g.p.y=418;run(g,{magic:true},1);assert.equal(g.activities[2].done,false);assert(C.activityHint(g).includes('0 / 3'));for(const c of g.carrots){g.p.x=c.x-40;run(g,{},100);}assert.equal(g.carrotCount,3);g.p.x=4250;run(g,{},100);run(g,{magic:true},1);assert(g.activities[2].done);assert.equal(g.candyCount,3);run(g,{},100);run(g,{magic:true},100);assert.equal(g.candyCount,3);assert.equal(g.carrotCount,3);});
test('Glasspausen fyller hjärtan och flygkraft och ger en trygg återstart',()=>{const g=game();g.p.x=3400;g.p.y=418;g.p.health=1;g.p.fuel=0;run(g,{magic:true},1);assert(g.activities[1].done);assert.equal(g.p.health,3);assert.equal(g.p.fuel,C.FUEL);assert(g.icecreamTime>0);assert.equal(g.checkpoint.x,3350);g.p.y=800;run(g,{},1);assert.equal(g.p.x,3350);assert.equal(g.p.health,2);run(g,{},300);assert.equal(g.p.health,2);run(g,{magic:true},1);assert.equal(g.p.health,2);});
test('Blomsterhopp ger extra höjd när man själv väljer att hoppa',()=>{const g=game();g.p.x=C.flowers[0]-g.p.w/2;run(g,{},40);assert(g.p.grounded);assert.equal(g.p.vy,0);run(g,{jump:true},1);assert(g.p.vy<-750);assert(g.notice.includes('Blomsterhopp'));});
test('Alla låga ridhinder kan hoppas över utan att förlora hjärtan',()=>{for(const h of C.hurdles){const g=game();g.p.x=h.x-110;run(g,{right:true},30);assert(g.p.x<=h.x-g.p.w);assert.equal(g.p.health,3);run(g,{right:true,jump:true},1);run(g,{right:true},100);assert(g.p.x>h.x+h.w);assert.equal(g.p.health,3);}});
test('Målet fungerar när alla samlarobjekt och små uppdrag hoppas över',()=>{const g=game();g.stars=[];g.candies=[];g.carrots=[];g.activities=[];rideToParty(g,false);assert.equal(g.mode,'won');assert.equal(g.collected,0);assert.equal(g.candyCount,0);assert.equal(g.carrotCount,0);});
test('Uppdrag och godsaker behålls efter skada, men nollställs vid nytt spel',()=>{const g=game();g.p.x=2350;g.p.y=418;run(g,{magic:true},1);g.p.y=800;run(g,{},1);assert(g.activities[0].done);assert.equal(g.candyCount,4);const fresh=C.createGame();assert.equal(fresh.candyCount,0);assert.equal(fresh.carrotCount,0);assert(fresh.activities.every(a=>!a.done));});
test('Paus fryser glassens belöningstid',()=>{const g=game();g.p.x=3400;g.p.y=418;run(g,{magic:true},1);const time=g.icecreamTime;g.mode='paused';run(g,{right:true,magic:true},300);assert.equal(g.icecreamTime,time);});
